-- ============================================================================
-- V1__init.sql — Initial schema for Resume Analyzer
-- Managed by Flyway.  Do NOT edit this file after it has been applied.
-- Add new migrations as V2__, V3__, etc.
-- ============================================================================

-- Users table (for registration-based auth)
CREATE TABLE IF NOT EXISTS app_users (
    id          BIGSERIAL PRIMARY KEY,
    username    VARCHAR(150) NOT NULL UNIQUE,
    password    VARCHAR(255) NOT NULL,
    email       VARCHAR(255),
    role        VARCHAR(50)  NOT NULL DEFAULT 'USER',
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Resume analysis history table
CREATE TABLE IF NOT EXISTS resume_analysis (
    id                    BIGSERIAL PRIMARY KEY,
    username              VARCHAR(150),
    filename              VARCHAR(500) NOT NULL,
    score                 INTEGER      NOT NULL,

    -- Section scores
    summary_score         INTEGER,
    skills_score          INTEGER,
    experience_score      INTEGER,
    formatting_score      INTEGER,
    professionalism_score INTEGER,

    -- Feedback text
    summary_feedback      TEXT,
    skills_feedback       TEXT,
    experience_feedback   TEXT,
    formatting_feedback   TEXT,
    overall_feedback      TEXT,

    -- ATS & keywords (stored as JSON arrays in TEXT columns)
    ats_score             INTEGER,
    ats_issues            TEXT,
    keywords_found        TEXT,
    keywords_missing      TEXT,
    missing_sections      TEXT,

    -- JD matching
    jd_match_score        INTEGER,

    -- Context
    industry              VARCHAR(100),
    submitted_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Index for user-specific queries (most common access pattern)
CREATE INDEX IF NOT EXISTS idx_resume_analysis_username
    ON resume_analysis (username, submitted_at DESC);

-- Index for anonymous analyses (null username)
CREATE INDEX IF NOT EXISTS idx_resume_analysis_submitted
    ON resume_analysis (submitted_at DESC);
